### ISSUE TITLE
[bug] assets path error

### ISSUE THREAD

**Issue by subframe7536** [Blackman99/joueur#2]
Windows 11, version 0.1.0

![image](https://user-images.githubusercontent.com/78338239/227710219-7c3916ec-4e4b-4a3b-bc65-96cd6ac86cb6.png)

**Comment by Blackman99** [comment]
This bug has already been fixed. Please wait for the next release.
Thanks for your feedback!

**Comment by Blackman99** [comment]
Fixed in [new release](https://github.com/Blackman99/joueur/releases/tag/Joueur-v0.1.1)
