### ISSUE TITLE
existingAlbum will always be undefined

### ISSUE THREAD

**Issue by abcdefghijorngarbosaxyz** [Blackman99/joueur#5]
https://github.com/Blackman99/joueur/blame/2e66a88a25b3fedb831a4ee9c992af74c8045dde/src/lib/db.ts#L77

The and() clause will return false value as al.songIds.includes(song.id) = false
Because a new song will have a new id, hence the new song id will not be in the album's song ids. Hence it will create a new index of album with the same title and artist.

**Comment by artcabrera** [comment]
The same happens here https://github.com/Blackman99/joueur/blame/2e66a88a25b3fedb831a4ee9c992af74c8045dde/src/lib/db.ts#L61

**Comment by abcdefghijorngarbosaxyz** [comment]
Closing this issue as INVALID. Noticed the error on my cloned repository that I've accidentally added a ! causing it to be false.
