### ISSUE TITLE
MODE "repeat-one" repeats one song endlessly

### ISSUE THREAD

**Issue by abcdefghijorngarbosaxyz** [Blackman99/joueur#6]
https://github.com/Blackman99/joueur/blob/b0f1b67f3cab6ee5ec44e1219f2b64aed700ec79/src/lib/store.ts#L93 the same audio gets loaded

Confirmed issue on release [v0.5.0](https://github.com/Blackman99/joueur/releases/tag/Joueur-v0.5.0)

**Comment by Blackman99** [comment]
Thanks for your feedback!

That's the expected behavior. 
"Repeat one" means play the current song over an over infinite times.
I think you're misunderstanding the difference between "Repeat one" and "Repeat once".

**Comment by Blackman99** [comment]
Maybe it is a better idea to change mode name to something like "cycle current"

**Comment by abcdefghijorngarbosaxyz** [comment]
> I think you're misunderstanding the difference between "Repeat one" and "Repeat once".

Yep i really did misunderstood "repeat one" and "repeat once"
